// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpksUuRO6Na9U9Kev0nxuu7YbDMeT-Cfs',
    appId: '1:903406229735:web:c562043cc528c2657faa42',
    messagingSenderId: '903406229735',
    projectId: 'biquetcafeteria',
    authDomain: 'biquetcafeteria.firebaseapp.com',
    storageBucket: 'biquetcafeteria.appspot.com',
    measurementId: 'G-FTGQGZYSV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkYgWLfNsxIND3FsWFn1d_IeS6wdH4kX4',
    appId: '1:903406229735:android:6f67b06fc470dfad7faa42',
    messagingSenderId: '903406229735',
    projectId: 'biquetcafeteria',
    storageBucket: 'biquetcafeteria.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsApl3ygC3pX55UFkRKrRd7CsOF6cIwSc',
    appId: '1:903406229735:ios:259384cdadafd3257faa42',
    messagingSenderId: '903406229735',
    projectId: 'biquetcafeteria',
    storageBucket: 'biquetcafeteria.appspot.com',
    iosBundleId: 'com.example.biquetCafeteria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsApl3ygC3pX55UFkRKrRd7CsOF6cIwSc',
    appId: '1:903406229735:ios:f0fd065c1daa9a027faa42',
    messagingSenderId: '903406229735',
    projectId: 'biquetcafeteria',
    storageBucket: 'biquetcafeteria.appspot.com',
    iosBundleId: 'com.example.biquetCafeteria.RunnerTests',
  );
}
