// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkzYt4lofjZHXzXPUW9UtuN71vfZpsd1M',
    appId: '1:34058484055:web:b47ef4b9e8c09a637e2612',
    messagingSenderId: '34058484055',
    projectId: 'biquet-cafeteria-3c689',
    authDomain: 'biquet-cafeteria-3c689.firebaseapp.com',
    storageBucket: 'biquet-cafeteria-3c689.appspot.com',
    measurementId: 'G-E10F418XMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9wyQzSCiv_bt_YEPk4loy8DDur_E46hI',
    appId: '1:34058484055:android:8eb075300d03075d7e2612',
    messagingSenderId: '34058484055',
    projectId: 'biquet-cafeteria-3c689',
    storageBucket: 'biquet-cafeteria-3c689.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBePBKn7tPs1KiF4mhfwM-a0MPMZG02h58',
    appId: '1:34058484055:ios:27b2f9ded5acafe17e2612',
    messagingSenderId: '34058484055',
    projectId: 'biquet-cafeteria-3c689',
    storageBucket: 'biquet-cafeteria-3c689.appspot.com',
    iosBundleId: 'com.example.biquetCafeteria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBePBKn7tPs1KiF4mhfwM-a0MPMZG02h58',
    appId: '1:34058484055:ios:181eb19b993496b07e2612',
    messagingSenderId: '34058484055',
    projectId: 'biquet-cafeteria-3c689',
    storageBucket: 'biquet-cafeteria-3c689.appspot.com',
    iosBundleId: 'com.example.biquetCafeteria.RunnerTests',
  );
}
